/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.brianestrada.vindecoder

import kotlin.system.measureNanoTime
import kotlin.test.Test


class VinDecoderTest {
    private val vin = "3GCUKPEC2EG109134"

    @Test
    fun perfTestCountry() {
        val loops = 100

        var totalTime = 0L

        VinDecoder(vin).getCountry()

        repeat(loops) {
            totalTime += measureNanoTime {
                VinDecoder(vin).getCountry()
            }
        }

        val averageTime = (totalTime / loops)

        println("Country totalTime ${totalTime / 1000}ms")
        println("Country averageTime ${averageTime}ns")
        println("====")
    }

    @Test
    fun perfTestMake() {
        val loops = 100

        var totalTime = 0L

        VinDecoder(vin).getMake()

        repeat(loops) {
            totalTime += measureNanoTime {
                VinDecoder(vin).getMake()
            }
        }

        val averageTime = (totalTime / loops)

        println("Make totalTime ${totalTime / 1000}ms")
        println("Make averageTime ${averageTime}ns")
        println("====")
    }
}
